export const AUTH_LOGIN_REQUESTED = 'AUTH_LOGIN_REQUESTED';
export const AUTH_LOGIN_SUCCEED   = 'AUTH_LOGIN_SUCCEED';
export const AUTH_LOGIN_FAILED    = 'AUTH_LOGIN_FAILED';
export const AUTH_LOGGED_IN       = 'AUTH_LOGGED_IN';
export const AUTH_LOGGED_OUT      = 'AUTH_LOGGED_OUT';
